### ISSUE TITLE
Why would you use this over something like Electron?

### ISSUE THREAD

**Issue by garygreen** [gabrielrcouto/php-gui#90]
Curious as to how php-gui compares. Both are targeted at builing cross platform apps, but surely php-gui is more a niche with it's own api (millions of devs already know HTML/CSS than a custom api to build a GUI).

When would you choose php-gui over something like Electron?

**Comment by reisraff** [comment]
https://github.com/gabrielrcouto/php-gui#why

**Comment by garygreen** [comment]
@reisraff you've linked to the readme which mentions nothing about electron, which this question is about specifically

**Comment by reisraff** [comment]
@garygreen I really don't know how to compare with electron, I don't like to tell in name to another people hahaha but I guess @gabrielrcouto made this not to have a battle with electron, and yes to have a new way to build applications with PHP.

**Comment by gabrielrcouto** [comment]
Hi @garygreen, thank you for the good question!

I choose PHP-GUI when I just want to share some PHP dev app using composer and get some help of people who are better in PHP than HTML/CSS/JS, or when I don’t want to open a browser to draw just a button.

PHP-GUI was created to be more like a “native” way to build GUIs, it’s like what C++ developers have, a UI library that can communicate with the Operational System UI API.

Electron is a really good way to make GUIs, and was my inspiration to build an easy to use GUI library. Unfortunately, because some PHP restrictions and the lack of knowledge of most PHP developers on installing extensions and dependencies, I had to use a bridge (Lazarus executable) between PHP and OS UI API, something like Electron did too, but using the browser.

For every App made with Electron, we need to open a browser, which has a high memory/CPU usage because need to instantiate a browser engine, rendering engine and JS interpreter (this is the most simple browser architecture). To draw a simple button, the browser need to parse the HTML, build the render tree, parse the CSS, build the layout of the render tree, and paint the button.

https://www.html5rocks.com/en/tutorials/internals/howbrowserswork/flow.png

For every App made with PHP-GUI, we need to open a Lazarus executable, which is a thin “layer” between PHP and OS GUI API. To draw a simple button, the Lazarus receive/send some messages from/to PHP using Pipe communication, build the render layout and paint the button.

Of course, Electron has lot of people working and optimizing it, not like PHP-GUI, what is more a proof-of-concept on the current project stage with small contributions. 

I need (with the help of community) to optimize the communication protocol (between PHP and Lazarus) for speed, build a packager in order to facilitate the app distribution and maybe build an IDE to easily create GUIs (just dragging and dropping components, like Lazarus IDE).

Building apps using HTML/CSS/JS (the Electron way) will be the future? Yes, I believe that some OS kernels, on the near future, will get some browser functionalities (like the JS Engine), which will contribute for a less memory/cpu consumption and a thinner layer between the browser and the operational system.

**Comment by garygreen** [comment]
Thanks for the detailed explanation. So php-gui is a good choice for building simple fast native GUI's, though if you need anything ui-complex, or are comfortable with frontend development and don't necessarily mind about memory / speed, Electron is possibly better suited.

> Building apps using HTML/CSS/JS (the Electron way) will be the future? Yes, I believe that some OS kernels, on the near future, will get some browser functionalities (like the JS Engine), which will contribute for a less memory/cpu consumption and a thinner layer between the browser and the operational system.

As a web developer, I hope this will happen. Thanks again 😄
